### ISSUE TITLE
How does this work with nested properties?

### ISSUE THREAD

**Issue by prevnode** [ember-bootstrap/ember-bootstrap-changeset-validations#23] opened 2020-05-26 23:09 UTC
Given a validation of a nested property: 

```
export default {
  amount: {
    value: [
      validatePresence(true),
      validateNumber({ integer: true }),
    ]
  }
};
```
How should a form element access the property in order to trigger the validation? 

```
<form.element
        @controlType='input'        
        @property='amount.value'
      />
```
doesn't seem to trigger the validation for me.

**Comment by jelhan** [comment] 2020-08-12 17:32
@basz adds a test case for multiple validations in #29. Does this answer your question?

**Comment by basz** [comment] 2020-08-13 09:50
@prevnode you code is correct. It should work. Make sure are using the latest ember-validations as it has been changed significantly lately. Also (actually probably the cause of the issue) using ember 3.16 was problematic for me. I upgraded to ember 3.20 which handles tracked properties better...

**Comment by jelhan** [comment] 2022-10-28 19:59
A path as `@property` is not officially supported by `<BsForm::Element>`. See https://github.com/ember-bootstrap/ember-bootstrap/issues/1173 for details. Closing this one for now. We can reopen after adding official support to Ember Bootstrap itself.

**Closed by jelhan** 2022-10-28 19:59 UTC
